### ISSUE TITLE
Generated (online) documentation is out of date

### ISSUE THREAD

**Issue by reem** [cgaebel/iobuf#11] opened 2015-04-16 20:36 UTC
Title says it all.

**Comment by cgaebel** [comment] 2015-04-16 21:01
http://www.rust-ci.org/cgaebel/iobuf

It looks fine... that's weird. Might you know what the problem is?

**Comment by cgaebel** [comment] 2015-04-28 03:57
I'm closing this since it seems to be forgotten about. Re-open if you have more info.

**Comment by reem** [comment] 2015-04-28 03:59
I have no idea what is causing it, but things are at least missing, e.g. AppendBuf.

**Comment by cgaebel** [comment] 2015-04-28 04:02
Oh god you're right. Even the fonts are different. Not sure what's different here... I'll dig into it.

**Comment by cgaebel** [comment] 2015-04-28 04:43
Ok I'm hosting them on github pages now. rust-ci is trashcan.

**Closed** 2015-04-28 04:42 UTC
